### ISSUE TITLE
Mac OS X support

### ISSUE THREAD

**Issue by pocallaghan** [ambimax/magento-patch#1]
Interesting approach. I gave the script a test run on my Mac (OS X 10.9.5) but unfortunately ran into a few compatibility issues. Not sure if you are worried about supporting Mac, but I figure I might as well report what I ran into.

``` bash
pocallaghan$ ./patch.sh 
./patch.sh: line 13: /Users/pocallaghan/Sites/magento: is a directory
Your Magento version is 1.7.0.2
./patch.sh: line 28: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
./patch.sh: line 31: 1.7.0.0-1.8.1.0/PATCH_SUPEE-4334_EE_1.11.0.0-1.13.0.2_v1.sh: syntax error: invalid arithmetic operator (error token is ".7.0.0-1.8.1.0/PATCH_SUPEE-4334_EE_1.11.0.0-1.13.0.2_v1.sh")
./patch.sh: line 119: 1.6.0.0-1.7.0.2/PATCH_SUPEE-2677_EE_1.13.0.2_v2.sh: syntax error: invalid arithmetic operator (error token is ".6.0.0-1.7.0.2/PATCH_SUPEE-2677_EE_1.13.0.2_v2.sh")
```

A quick glance suggests the `mage-mirror` repo you credit may also have the same compatibility issues. I don't have time at the moment, but if nobody else picks this up in the mean time, I'm willing to have a crack at making it more universal.

**Comment by ambimax** [comment]
Thanks for the report. We do not plan to support mac as development is on linux only (vm). But we are glad if you like to improve it.
